backend:
  name: github
  repo: tocteman/ubank_app
  branch: master

publish_mode: editorial_workflow
media_folder: src/img/uploads

collections:
  - name: blog
    label: Blog
    folder: src/pages/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: thumbnail, label: Featured Image, widget: image }
      - { name: title, label: Title }
      - { name: "body", label: "Blog post content", widget: "markdown"}
